project:
  type: website
  output-dir: docs

website:
  title: "Life Course Methods for BMI and Inflammation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: appendix.qmd
        text: Supplementary Appendix
    right:
      - icon: github
        href: https://github.com/sameratshan/LifecourseMethods

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    link-citations: true
